### ISSUE TITLE
Compile / Link error due to I2S_GetInputClock

### ISSUE THREAD

**Issue by SuperThunder** [pea-pod/mbed-stm32-i2s#1]
This is the same error I encountered with the ST library so I think it's probably something to do with my mbed setup,
I'm using the latest mbed studio and mbed-os 6.2.1. 
I switched from my custom board target to the NUCLEO-F411RE / NUCLEO-F429ZI targets and still encountered the issue.

```
Compile [ 99.6%]: stm_spi_api.c
Compile [ 99.7%]: StmI2sPeripheralPins.c
Compile [ 99.8%]: stm_dma_api.c
Compile [ 99.9%]: stm_i2s_api.c
[Warning] stm_i2s_api.c@843,14: implicit declaration of function 'I2S_GetInputClock' is invalid in C99 [-Wimplicit-function-declaration]
Compile [100.0%]: I2S.cpp
Link: mbed-os-6-peapod-ST_I2S
[Warning] @0,0: L3912W: Option 'legacyalign' is deprecated.
[Error] @0,0: L6218E: Undefined symbol I2S_GetInputClock (referred from BUILD/NUCLEO_F429ZI/ARMC6/mbed-stm32-i2s/ST_I2S/targets/TARGET_STM/stm_i2s_api.o).
Warning: L3912W: Option 'legacyalign' is deprecated.
Error: L6218E: Undefined symbol I2S_GetInputClock (referred from BUILD/NUCLEO_F429ZI/ARMC6/mbed-stm32-i2s/ST_I2S/targets/TARGET_STM/stm_i2s_api.o).
Finished: 0 information, 1 warning and 1 error messages.
[ERROR] Warning: L3912W: Option 'legacyalign' is deprecated.
Error: L6218E: Undefined symbol I2S_GetInputClock (referred from BUILD/NUCLEO_F429ZI/ARMC6/mbed-stm32-i2s/ST_I2S/targets/TARGET_STM/stm_i2s_api.o).
Finished: 0 information, 1 warning and 1 error messages.
```

Which I traced to line 843 of stm_i2s_api.c in the TARGET_STM32F4 folder. The error is completely right that I2S_GetInputClock is not defined anywhere. Looking in Google I did find an old HAL file [stm32f4xx_hal_i2s_ex.c which contains it](https://github.com/cnoviello/mastering-stm32/blob/master/nucleo-f411RE/system/src/stm32f4xx/stm32f4xx_hal_i2s_ex.c).

so back in my project I found the STM32F4 HAL I2S drivers at mbed-os/targets/<STM subdirectories>/STM32F4xx_HAL_driver/stm32f4xx_hal_i2s{.c, .h, _ex.c, _ex.h}.

where the I2S_GetInputClock function appears to have been deleted at some point.
Searching around I didn't see any obvious renames or replacements.

edit: It appears I2S_GetInputClock dissapeared sometime in late 2016 / early 2017, still present in Oct 2016: https://github.com/ARMmbed/mbed-os/blob/26ced98734a3b07f5d62a2be2de266e268e75687/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s_ex.c

finally tracked it down to this commit: https://github.com/ARMmbed/mbed-os/commit/39d981cf70b4dc3994de7218504c381c580329db#diff-1a07cb8f608d4330c9cc3e3c30e1c4c6

It was the move from STM32 HAL v1.5.0 to v1.7.1 on May 17, 2017 with a commit titled "STM32Cube_FW_F4_V1.16.0".

What mbed environment / versions are you using? It seems like mbed 5.3 should be the last version for which the ST I2S library will work given the removed I2S_GetInputClock function.

**Comment by pea-pod** [comment]
I'm very sorry. I had started to dig down into the commits to figure out about the I2S as you referenced it, but I could not find anything on it. I now understand why that is. 😁 

Both mbed-os 5.3 and the ST HAL are very old, at least by those standards. I know that the files I got from the mbed.com repo were from that year, but could have been from newer.

Regarding the version I am using, I pulled down what was the latest at the time.  This would be at least 6.0, if not newer. I know this, because the earlier versions included a file that is no longer present in 6.0, necessitating my changes.

I am also using `gcc` and the Python mbed compiling library. 

I have an idea however, but I am not adept enough to know how to test it without more digging.

I believe the mbed compile routines have linker optimization enabled. I do not call the highest level `I2S::harmonize` function, so it and everything it needs never gets referenced, and subsequently dropped. This is just a theory, however but it seems like it could make sense. I do not know what flags are enabled for `arm6`, but even if it were enabled, it's conceivable that it would drop it.

The call chain for this is:
`I2S::harmonize` in `drivers/I2S.cpp`
`i2s_harmonize` in `targets/TARGET_STM/TARGET_STM32F4/stm_i2s_api.c`
`i2s_compute_real_frequency` in `targets/TARGET_STM/TARGET_STM32F4/stm_i2s_api.c`
`i2s_compute_closest_frequency` in `targets/TARGET_STM/TARGET_STM32F4/stm_i2s_api.c`
`I2S_GetInputClock` in `targets/TARGET_STM/TARGET_STM32F4/stm_i2s_api.c`

and presumably, this would be included in a roundabout way from the older I2S ex file as you mentioned.

I will look through it to see if there's a suitable replacement, otherwise, @jeromecoutant or one of his peers would probably need to help.

**Comment by pea-pod** [comment]
I think it might be possible to glean the intent of that function from that old file you referenced and then see what is available for the current HAL file. I believe that the `HAL_I2S_Init` function in the `stm32fxx_hal_i2s.c` function has logic pertaining to the clock value. It might even be directly in the structure now, although I did not do enough detective work to figure that out yet.

**Comment by jeromecoutant** [comment]
Hi

I don't think I can help about this very very old function... :-(

Just make a quick grep on code, and found:
https://github.com/STMicroelectronics/STM32CubeF4/blob/master/Projects/STM324x9I_EVAL/Examples/I2S/readme.txt

Hope some ex cold help....

**Comment by SuperThunder** [comment]
@pea-pod Ahhh, that makes sense, good thinking with the linker optimization. For now I just hardcoded a value to i2sclk to avoid the call to I2S_GetInputClock. I used 48khz, probably wrong, but I have to read up on where the I2S peripheral gets its clock from.

I'm using mbed studio, so while there seem to be a couple of ways to enable LTO (config files, compile by CLI), I'm sticking with my simple hack for now. I2S.h doesn't cause link errors anymore so that's a good start, I need to write a test application now.

@jeromecoutant Thank you for the examples, they look to be very useful for learning about using the stm32 I2S peripheral.


I consider my linker issues figured out, so I'll close the issue now. Thanks pea-pod and jerome!
